FROM nvcr.io/nvidia/tensorrt:24.03-py3

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV TZ=Etc/UTC

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    build-essential \
    python3.10\
    python3-pip \
    python3-venv  \
    libfreeimage3 \
    libgl1 \
    libglib2.0-0 \
    libgles2-mesa-dev \
    libglfw3-dev \
    libxkbcommon-x11-0 \ 
    libsm6 \
    libxrender1 \
    libxi6 \ 
    libxext6 \
    libxrender1 \
    libxkbcommon0 \
    && rm -rf /var/lib/apt/lists/*
    
# Set up the working directory
RUN mkdir -p /workspace/LWDETR
WORKDIR /workspace/LWDETR

ADD requirements.txt requirements.txt
RUN pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124
RUN pip install opencv-python==4.12.0.88
RUN pip install -r requirements.txt
# Install deploy dependencies
ADD deploy/requirements.txt requirements_deploy.txt
RUN pip install -r requirements_deploy.txt
RUN pip install matplotlib==3.10.7
RUN pip install imageio==2.37.0
RUN pip install trimesh
RUN pip install tensorboard
RUN pip install torch-tb-profiler==0.4.3
RUN python -m pip install --upgrade pip
COPY . /workspace/LWDETR
# Do this in side the container after starting it the first time:
# Compiling CUDA operators
# cd /workspace/LWDETR/models/ops
#  python setup.py build install
# python test.py

